apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  labels:
    io.kompose.service: data
  name: data
spec:
  selector:
    matchLabels:
      io.kompose.service: data
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: data
    spec:
      containers:
        - image: aselzk/quotes-data:v1
          name: db
          envFrom:
          - secretRef:
              name: data-secret
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: asel-claim
            mountPath: /var/lib/mysql
            subPath: mysql
      volumes:
      - name: asel-claim
        persistentVolumeClaim:
          claimName: asel-claim
status: {}

---

apiVersion: v1
kind: Secret
metadata:
  name: data-secret
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: eWVz
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  labels:
    io.kompose.service: data
  name: data
spec:
  type: ClusterIP
  selector:
    io.kompose.service: data
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306

